### ISSUE TITLE
GMT time for xmlDateFormatWithMilli

### ISSUE THREAD

**Issue by pierrelfn** [himanshu-soni/gpx-parser#18]
Hi
I got problems in decoding dates in a GPX file, mixing points with dates in xmlDateFormat, other ones in xmlDateFormatWithMilli. There was a difference of two hours between two consecutive points (in France).
According to me, the line in BaseGPX 
xmlDateFormat.setTimeZone(TimeZone.getTimeZone("GMT")); 
should be followed by this one xmlDateFormatWithMilli.setTimeZone(TimeZone.getTimeZone("GMT"));
But, it's just a suggestion...

**Comment by ThomasDaheim** [comment]
Shame on me - I introduced the new format and forgot to set the time zone for it...

Will include and create a pull request here.

**Comment by ThomasDaheim** [comment]
Done, waiting for @himanshu-soni to include pull request.

@pierrelfn: You could use my branch in the meantime if not too much trouble to switch...
