### ISSUE TITLE
Element (Waypoints, Routes, etc) should be saved in chronological order 

### ISSUE THREAD

**Issue by dinzdale** [himanshu-soni/gpx-parser#19]
Our Android app uses this nice library for saving routes to gpx files for developer playback and analysis when recording sales team on field drives. This requires the building of the route to save each element by insertion order (regardless of timestamp). Changing collection of points in GPX.java to LinkedHashSet instead of HashSet helps to maintain the insertion order:

ex: 
       private Metadata metadata;
	private Set<Route> routes;
	private Set<Track> tracks;
	private Set<Waypoint> waypoints;

	public GPX() {
		this.waypoints = new LinkedHashSet<>();
		this.tracks = new LinkedHashSet<>();
		this.routes = new LinkedHashSet<>();
	}

I have tested the generated gpx files in the Android Studio emulator as well as Lockito, which is a mock location provider that is capable of replaying imported gpx files.
I have fix which I can provide a branch for a pull request, but I don't have permission to push the branch.

Thanks,
GJ

**Comment by ThomasDaheim** [comment]
Why don't you create a pull request? Thats how my changes found their way into this repo...

**Comment by dinzdale** [comment]
Like I said in my post, I don't have write permissions to create a branch
on which to create a pull request.

Thanks,
Gary

**Comment by dinzdale** [comment]
Himanshu, Thomas,
   Pull requested created. I didn't realize I needed to fork the repo first.

Thanks,
GJ
