### ISSUE TITLE
Parse ISO 6801 date using Instant.parse()

### ISSUE THREAD

**Issue by ThomasDaheim** [himanshu-soni/gpx-parser#3]
Hi,

I have issues with iso6801 dates in tracks:

<time>2017-05-14T08:13:59Z</time>

is converted into 08:13:59 CEST instead of 08:13:59 GMT.

So I changed GPXParser.getNodeValueAsDate to

```
final String dateSting = 
    node.getFirstChild().getNodeValue().replaceAll("([0-9\\-T]+:[0-9]{2}:[0-9.+]+):([0-9]{2})", "$1$2");
final Instant instant = Instant.parse(dateSting);
val = Date.from(instant);
return val;
```

Which seems to work nicely.

**Comment by ThomasDaheim** [comment]
Alternatively, you could do

```
BaseGPX() {
        // TF, 20170515: iso6801 dates are always in GMT timezone
        xmlDateFormat.setTimeZone(TimeZone.getTimeZone("GMT"));
}

```

**Comment by himanshu-soni** [comment]
@ThomasDaheim thanks, I will update it.

**Comment by ThomasDaheim** [comment]
Great, thanks. It worked on the few examples I had - maybe you have a bigger test suit to verify for a larger set of files?
