### ISSUE TITLE
Can we parse an GPX which contains Extensions

### ISSUE THREAD

**Issue by prasad456** [himanshu-soni/gpx-parser#4]
How can I parse Extensions which are in GPX file.
Here sample file for GPX which are having extensions [click here](https://github.com/ticofab/android-gpx-parser/files/1054065/sample.txt)

**Comment by himanshu-soni** [comment]
Hi @prasad456, you can extend `IExtensionParser` and add your extension parser to GPX parser using `addExtensionParser()` method. an example is given as well. Please see [DummyExtensionParser](https://github.com/himanshu-soni/gpx-parser/blob/master/src/com/hs/gpxparser/extension/DummyExtensionParser.java) sample implementation.

**Comment by prasad456** [comment]
Hi @himanshu-soni ,

I couldn't find the DummyExtensionParser Sample which you attached and I have to parse from URL.
Can parse GPX from URL by using this library? 
I parsed GPX from URL by using another library, but That library can't supporting extensions, as you said.

**Comment by himanshu-soni** [comment]
Hi @prasad456 Yes this library doesn't support parsing from url. But it does support extensions. please check the url now:
https://github.com/himanshu-soni/gpx-parser/blob/master/src/com/hs/gpxparser/extension/DummyExtensionParser.java

**Comment by prasad456** [comment]
Hi @himanshu-soni But I need to parse from URL?
How could make this?
